# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Democratizing Data
description: >- # this means to ignore newlines until "baseurl:"
  A Search And Discovery Platform For Public Data Assets.
email: democratizing.data.project@gmail.com

# URL settings
domain: democratizingdata.ai       # if you want to force HTTPS, specify the domain
url: "https://democratizingdata.ai" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""          # the subpath of your site, e.g. /blog

# SEO and Performance
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Collections
collections:
  events:
    output: true
    permalink: /:collection/:year/:title/
  tools:
    output: true
    permalink: /:collection/:title/
  resources:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "default"

include:
  - CNAME

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Task Master AI files
  - tasks/
  - scripts/
  - .taskmasterconfig
  # Cursor IDE files
  - .cursor/
  - .windsurfrules
  - .roomodes
  # Git and development files
  - .git/
  - .gitignore
  - README.md
  - LICENSE
  # Original SCSS files (now in _sass)
  - assets/scss/
